---
version: '3'

networks:
  internalnet:

services:
  compilertron:
    image: unxmaal/compilertron:latest
    container_name: compilertron
    hostname: compilertron
    ports:
      - "8086:8086"
      - "8188:8188"
    networks:
      - internalnet
