---
version: '3'

# networks:
#   internalnet:

services:
  compilertron:
    image: bca50fe928c9 #unxmaal/compilertron:old
    container_name: compilertron
    hostname: compilertron
    ports:
      - "8086:8086"
      - "8186:8186"
    # networks:
    #   - internalnet
