- name: Get the gcc builder script
  copy:
    src: files/build_gcc.sh
    dest: /opt/build_gcc.sh
    owner: root
    group: root
    mode: 0755
- name: Run the gcc builder script
  command: "./build_gcc.sh"
  retries: 3
  register: result
  until: result.rc == 0
  args:
    chdir: "/opt"
- name: clean up mips-sgi-irix6.5
  file:
    dest: /opt/gcc/mips-sgi-irix6.5
    state: absent
- name: create mips-sgi-irix6.5
  file:
    path: "/opt/gcc/mips-sgi-irix6.5"
    state: directory
- name: Create mips-sgi-irix6.5 binutils symlink
  file:
    src: /opt/binutils/mips-sgi-irix6.5/bin
    dest: /opt/gcc/mips-sgi-irix6.5/bin
    state: link
- name: Create sys-include symlink
  file:
    src: /opt/irix-root/usr/include
    dest: /opt/gcc/mips-sgi-irix6.5/sys-include
    state: link