# Setup the virt OS
- import_tasks: setup_virt_os.yml
# Add 50gb opt vol
- import_tasks: setup_compile_vol.yml
# Set up gcc
- import_tasks: setup_gcc.yml
# *) copy irix /lib32 /usr/lib32 /usr/include somewhere so that the structure is still intact - for example, $HOME/irix-root

# *) build binutils-2.17

# ./configure --target=mips-sgi-irix6.5 --prefix=$HOME/irix-binutils --with-sysroot=$HOME/irix-root --enable-werror=no
# make 
# make install

# *) add $HOME/irix-binutils/bin to your path

# *) create a separate build directory for gcc 4.7.4 and enter it

# *) run these commands - note how the configure script is run from other directory:

# export AS_FOR_TARGET="mips-sgi-irix6.5-as"
# export LD_FOR_TARGET="mips-sgi-irix6.5-ld"
# export NM_FOR_TARGET="mips-sgi-irix6.5-nm"
# export OBJDUMP_FOR_TARGET="mips-sgi-irix6.5-objdump"
# export RANLIB_FOR_TARGET="mips-sgi-irix6.5-ranlib"
# export STRIP_FOR_TARGET="mips-sgi-irix6.5-strip"
# export READELF_FOR_TARGET="mips-sgi-irix6.5-readelf"
# export target_configargs="--enable-libstdcxx-threads=no"

# $HOME/src/gcc-4.7.4/configure --enable-obsolete --disable-multilib --prefix=$HOME/irix-gcc --target=mips-sgi-irix6.5 --disable-nls --enable-languages=c,c++

# make

# *) creating gcc info file may fail - in that case, just touch gcc/doc/gcc.info and restart make

# *) libstdc++ may have a couple of issues building but it is buildable
#  - please tell when you hit them, they can be circumvented by slightly
#  editing c++config.h (possibly this could be done in crossconfig.m4
#  already)

