- name: Create src dir
  file:
    path: /opt/src
    state: directory
    
- name: Fetch gcc-4_7-irix zip
  get_url:
    url: "{{ gcc_zip }}"
    dest: "/opt/src/gcc-4_7-irix.zip"

- debug:
    msg: "The next task Extracting gcc may take up to 10-20 min......."

- name: Extracting gcc zip into /opt/src
  unarchive:
    src: "/opt/src/{{  gcc_zip | urlsplit('path') | basename }}"
    dest: "/opt/src"
    copy: no
    creates: "/opt/src/gcc/ltgcc.m4"

- name: Stat poorly-named gcc dir
  stat: path=/opt/src/gcc-gcc-4_7-irix
  register: dumb_gcc_path

- name: Remove old gcc src
  file: 
    path: /opt/src/gcc
    state: absent
  when: dumb_gcc_path.stat.exists

- name: Fix gcc path
  command: mv /opt/src/gcc-gcc-4_7-irix /opt/src/gcc
  when: dumb_gcc_path.stat.exists

- name: Create empty gcc-build dir
  file:
    path: "/opt/src/gcc-build"
    state: directory

- name: Fetch irix-root
  get_url:
    url: "{{ irix_root }}"
    dest: "/opt/{{  irix_root | urlsplit('path') | basename }}"

- name: Create irix-root directory
  file:
    path: "/opt/irix-root"
    state: directory

- name: Extract irix-root tarball
  unarchive:
    src: "/opt/{{  irix_root | urlsplit('path') | basename }}"
    dest: "/opt/irix-root"
    copy: no
    creates: "/opt/irix-root/usr/lib32/yaccpar"

- name: Fixup GCC build - create mips-sgi-irix6.5 dir
  file:
    path: "/opt/gcc/mips-sgi-irix6.5"
    state: directory

- name: Fixup GCC build - symlink for sys-includes
  file:
    src: "/opt/irix-root/usr/include"
    dest: "/opt/gcc/mips-sgi-irix6.5/sys-include"
    state: link

- name: Fixup GCC build - symlink for /usr/lib32
  file:
    src: "/opt/irix-root/usr/lib32"
    dest: "/usr/lib32"
    state: link

- name: Fixup GCC build - replace stdlib_core.h
  copy:
    src: "files/stdlib_core.h"
    dest: "/opt/gcc/mips-sgi-irix6.5/sys-include/internal"
    owner: root
    group: root
    mode: 0755
