# - name: Fetch sgug-rse zip
#   get_url:
#     url: "{{ sgug_rse }}"
#     dest: "/opt/src/sgug-rse-srpms-0.0.3alpha.tar.gz"


# gcc
- name: Install the gcc srpm
  command:
    cmd: rpm -Uvh /opt/sgug/rpmbuild/SRPMS/gcc-9.2.0-1.sgugalpha.src.rpm

- name: Remove gcc source dir
  file:
    path: /root/rpmbuild/SOURCES/gcc-9.2.0-20190812
    state: absent

- name: Create gcc source dir
  file:
    path: /root/rpmbuild/SOURCES/gcc-9.2.0-20190812
    state: directory

- name: extract the source tarball
  unarchive:
    src: /root/rpmbuild/SOURCES/gcc-9.2.0-20190812.tar.gz
    dest: /root/rpmbuild/SOURCES
    remote_src: yes

- name: copy patcher
  copy:
    src: files/patch_gcc.sh
    dest: /opt/sgug/patch_gcc.sh
    mode: 0755

- name: run patch_gcc.sh
  command:
    cmd: /opt/sgug/patch_gcc.sh

- name: Get the gcc builder script
  copy:
    src: files/build_gcc.sh
    dest: /opt/sgug/build_gcc.sh
    mode: 0755


# - name: Stat poorly-named gcc dir
#   stat: path=/opt/src/gcc-gcc-4_7-irix
#   register: dumb_gcc_path

# - name: Remove old gcc src
#   file: 
#     path: /opt/src/gcc
#     state: absent
#   when: dumb_gcc_path.stat.exists

# - name: Fix gcc path
#   command: mv /opt/src/gcc-gcc-4_7-irix /opt/src/gcc
#   when: dumb_gcc_path.stat.exists

# - name: Create empty gcc-build dir
#   file:
#     path: "/opt/src/gcc-build"
#     state: directory

# - name: Fetch irix-root
#   get_url:
#     url: "{{ irix_root }}"
#     dest: "/opt/{{  irix_root | urlsplit('path') | basename }}"




# - name: Fixup GCC build - create mips-sgi-irix6.5 dir
#   file:
#     path: "/opt/gcc/mips-sgi-irix6.5"
#     state: directory

# - name: Fixup GCC build - symlink for sys-includes
#   file:
#     src: "/opt/irix-root/usr/include"
#     dest: "/opt/gcc/mips-sgi-irix6.5/sys-include"
#     state: link

# - name: Fixup GCC build - symlink for /usr/lib32
#   file:
#     src: "/opt/irix-root/usr/lib32"
#     dest: "/usr/lib32"
#     state: link

# - name: Fixup GCC build - replace stdlib_core.h
#   copy:
#     src: "files/stdlib_core.h"
#     dest: "/opt/gcc/mips-sgi-irix6.5/sys-include/internal"
#     owner: root
#     group: root
#     mode: 0644

# - name: Fixup GCC build - replace gcc.texi
#   copy:
#     src: "files/gcc.texi"
#     dest: "/opt/src/gcc/gcc/doc/"
#     owner: root
#     group: root
#     mode: 0644
