# Setup the virt OS
- name: Set hostname
  hostname: 
    name: compilertron

#- apt_repository:
#    repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu devel main
#    state: present

# - name: Add an apt key 
#   apt_key:
#     keyserver: keyserver.ubuntu.com
#     id: 93C4A3FD7BB9C367

- name: Install required packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - build-essential
    - bison
    - flex
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev
    - parted
    - texinfo 
    - git 
    - unzip
    - openssh-server
    - autoconf
    - gettext
