- name: Fetch gcc
  get_url:
    url: "{{ gcc_zip }}"
    dest: /opt/src
- name: Extracting gcc
  unarchive:
    src: "/opt/{{  gcc_zip | urlsplit('path') | basename }}"
    dest: /opt/src/gcc
    copy: no
    creates: /opt/src/gcc/ltgcc.m4
- name: create gcc-build dir
  file:
    path: /opt/build/gcc
    state: directory
- name: Fetch irix-root
  get_url:
    url: "{{ irix_root }}"
    dest: "/opt/{{  irix_root | urlsplit('path') | basename }}"
- name: create irix-root
  file:
    path: /opt/irix-root
    state: directory
- name: Extracting irix-root
  unarchive:
    src: "/opt/{{  irix_root | urlsplit('path') | basename }}"
    dest: /opt/irix-root
    copy: no
    creates: /opt/irix-root/usr/lib32/yaccpar

