# - name: Fetch sgug-rse zip
#   get_url:
#     url: "{{ sgug_rse }}"
#     dest: "/opt/src/sgug-rse-srpms-0.0.3alpha.tar.gz"
- name: Create /opt/sgug directory $PREFIX
  file:
    path: "/opt/sgug"
    state: directory

- name: Create irix-root directory $IRIX
  file:
    path: "/opt/irix-root"
    state: directory

- name: copy file
  copy:
    src: irix-root.6.5.30.tar.bz2
    dest: /opt/irix-root.6.5.30.tar.bz2

- name: copy file
  copy:
    src: sgug-rse-srpms-0.0.3alpha.tar.gz
    dest: /opt/sgug-rse-srpms-0.0.3alpha.tar.gz

- name: Extract irix-root tarball
  unarchive:
    src: "/opt/{{  irix_root | urlsplit('path') | basename }}"
    dest: "/opt/irix-root"
    copy: no
    creates: "/opt/irix-root/usr/lib32/yaccpar"

- name: Extracting rse zip into /opt/sgug
  unarchive:
    src: "/opt/sgug-rse-srpms-0.0.3alpha.tar.gz"
    dest: "/opt/sgug"
    copy: no
    #creates: "/opt/src/gcc/ltgcc.m4"

# binutils
- name: Install the binutils srpm
  command:
    cmd: rpm -Uvh /opt/sgug/rpmbuild/SRPMS/binutils-2.23.2-24.sgugalpha.src.rpm

- name: Remove gcc source dir
  file:
    path: /root/rpmbuild/SOURCES/binutils-2.23.2
    state: absent

- name: Create binutils source dir
  file:
    path: /root/rpmbuild/SOURCES/binutils-2.23.2
    state: directory

- name: extract the source tarball
  unarchive:
    src: /root/rpmbuild/SOURCES/binutils-2.23.2.tar.gz
    dest: /root/rpmbuild/SOURCES
    remote_src: yes

# Patch04: binutils-2.22.52.0.4-no-config-h-check.patch
- name: apply patch 4
  patch:
    src: /root/rpmbuild/SOURCES/binutils-2.22.52.0.4-no-config-h-check.patch
    basedir: /root/rpmbuild/SOURCES/binutils-2.23.2
    strip: 1
    remote_src: yes
# Patch60: binutils2_23.sgifixes.patch
- name: apply patch 60
  patch:
    src: /root/rpmbuild/SOURCES/binutils2_23.sgifixes.patch
    basedir: /root/rpmbuild/SOURCES/binutils-2.23.2
    strip: 1
    remote_src: yes
# Patch61: binutils.sgirelinkfix.patch
- name: apply patch 61
  patch:
    src: /root/rpmbuild/SOURCES/binutils.sgirelinkfix.patch
    basedir: /root/rpmbuild/SOURCES/binutils-2.23.2
    strip: 1
    remote_src: yes
# Patch62: binutils.ldirixn32paths.patch
- name: apply patch 62
  patch:
    src: /root/rpmbuild/SOURCES/binutils.ldirixn32paths.patch
    basedir: /root/rpmbuild/SOURCES/binutils-2.23.2
    strip: 1
    remote_src: yes

- name: copy make_binutils.sh
  copy:
    src: files/make_binutils.sh
    dest: /opt/sgug/make_binutils.sh
    mode: 0755

- name: run make_binutils.sh
  command:
    cmd: /opt/sgug/make_binutils.sh


# gcc
- name: Install the gcc srpm
  command:
    cmd: rpm -Uvh /opt/sgug/rpmbuild/SRPMS/gcc-9.2.0-1.sgugalpha.src.rpm

- name: Remove gcc source dir
  file:
    path: /root/rpmbuild/SOURCES/gcc-9.2.0-20190812
    state: absent

- name: Create gcc source dir
  file:
    path: /root/rpmbuild/SOURCES/gcc-9.2.0-20190812
    state: directory

- name: extract the source tarball
  unarchive:
    src: /root/rpmbuild/SOURCES/gcc-9.2.0-20190812.tar.gz
    dest: /root/rpmbuild/SOURCES
    remote_src: yes

- name: copy patcher
  copy:
    src: files/patch_gcc.sh
    dest: /opt/sgug/patch_gcc.sh
    mode: 0755

- name: run patch_gcc.sh
  command:
    cmd: /opt/sgug/patch_gcc.sh

# - name: Stat poorly-named gcc dir
#   stat: path=/opt/src/gcc-gcc-4_7-irix
#   register: dumb_gcc_path

# - name: Remove old gcc src
#   file: 
#     path: /opt/src/gcc
#     state: absent
#   when: dumb_gcc_path.stat.exists

# - name: Fix gcc path
#   command: mv /opt/src/gcc-gcc-4_7-irix /opt/src/gcc
#   when: dumb_gcc_path.stat.exists

# - name: Create empty gcc-build dir
#   file:
#     path: "/opt/src/gcc-build"
#     state: directory

# - name: Fetch irix-root
#   get_url:
#     url: "{{ irix_root }}"
#     dest: "/opt/{{  irix_root | urlsplit('path') | basename }}"




# - name: Fixup GCC build - create mips-sgi-irix6.5 dir
#   file:
#     path: "/opt/gcc/mips-sgi-irix6.5"
#     state: directory

# - name: Fixup GCC build - symlink for sys-includes
#   file:
#     src: "/opt/irix-root/usr/include"
#     dest: "/opt/gcc/mips-sgi-irix6.5/sys-include"
#     state: link

# - name: Fixup GCC build - symlink for /usr/lib32
#   file:
#     src: "/opt/irix-root/usr/lib32"
#     dest: "/usr/lib32"
#     state: link

# - name: Fixup GCC build - replace stdlib_core.h
#   copy:
#     src: "files/stdlib_core.h"
#     dest: "/opt/gcc/mips-sgi-irix6.5/sys-include/internal"
#     owner: root
#     group: root
#     mode: 0644

# - name: Fixup GCC build - replace gcc.texi
#   copy:
#     src: "files/gcc.texi"
#     dest: "/opt/src/gcc/gcc/doc/"
#     owner: root
#     group: root
#     mode: 0644
