- name: Partition the compile volume
  parted:
    device: /dev/sdb
    number: 1
    state: present
- name: Create a ext4 filesystem on /dev/sdb1
  filesystem:
    fstype: ext4
    dev: /dev/sdb1
- name: Mount sdb1 at /opt
  mount:
    path: /opt
    src: /dev/sdb1
    fstype: ext4
    state: mounted