- name: Create scratch
  file:
    path: /opt/scratch
    state: directory
- name: Copy hello.c
  copy:
    src: "files/hello.c"
    dest: "/opt/scratch/hello.c"
    owner: root
    group: root
    mode: 0744
- name: Copy build_hello
  copy:
    src: "files/build_hello.sh"
    dest: "/opt/scratch/build_hello.sh"
    owner: root
    group: root
    mode: 0755
- name: Build hello.c
  command: "./build_hello.sh"
  args:
    chdir: "/opt/scratch" 
- name: test hello output
  shell: "file /opt/scratch/hello | grep MIPS"
  register: result
  failed_when: "result.rc != 0"

- name: move test file to NFS if available
  copy:
    src:        "/opt/scratch/hello"
    dest:       "{{ nfs_path}}"
    owner:      nobody
    group:      nobody
    mode:       0755
  when:         use_nfs